import { sqliteTable, text, integer, real, blob } from 'drizzle-orm/sqlite-core';

export const recordings = sqliteTable('recordings', {
  id: text('id').primaryKey(),
  title: text('title'),
  filePath: text('file_path').notNull(),
  duration: integer('duration').notNull().default(0),
  format: text('format').notNull().default('m4a'),
  sizeBytes: integer('size_bytes').notNull().default(0),
  language: text('language').default('en'),
  isMeeting: integer('is_meeting', { mode: 'boolean' }).notNull().default(false),
  isFavorite: integer('is_favorite', { mode: 'boolean' }).notNull().default(false),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
  syncedAt: text('synced_at'),
});

export const transcripts = sqliteTable('transcripts', {
  id: text('id').primaryKey(),
  recordingId: text('recording_id')
    .notNull()
    .references(() => recordings.id, { onDelete: 'cascade' }),
  content: text('content').notNull(),
  language: text('language').notNull().default('en'),
  engine: text('engine').notNull().default('whisper-local'),
  confidence: real('confidence'),
  segments: text('segments'),
  createdAt: text('created_at').notNull(),
});

export const translations = sqliteTable('translations', {
  id: text('id').primaryKey(),
  transcriptId: text('transcript_id')
    .notNull()
    .references(() => transcripts.id, { onDelete: 'cascade' }),
  targetLanguage: text('target_language').notNull(),
  content: text('content').notNull(),
  engine: text('engine').notNull(),
  createdAt: text('created_at').notNull(),
});

export const aiOutputs = sqliteTable('ai_outputs', {
  id: text('id').primaryKey(),
  recordingId: text('recording_id')
    .notNull()
    .references(() => recordings.id, { onDelete: 'cascade' }),
  type: text('type').notNull(),
  content: text('content').notNull(),
  engine: text('engine').notNull(),
  prompt: text('prompt'),
  createdAt: text('created_at').notNull(),
});

export const tags = sqliteTable('tags', {
  id: text('id').primaryKey(),
  name: text('name').notNull().unique(),
  color: text('color'),
});

export const recordingTags = sqliteTable('recording_tags', {
  recordingId: text('recording_id')
    .notNull()
    .references(() => recordings.id, { onDelete: 'cascade' }),
  tagId: text('tag_id')
    .notNull()
    .references(() => tags.id, { onDelete: 'cascade' }),
  isAutoGenerated: integer('is_auto_generated', { mode: 'boolean' }).notNull().default(false),
});

export const embeddings = sqliteTable('embeddings', {
  id: text('id').primaryKey(),
  recordingId: text('recording_id')
    .notNull()
    .references(() => recordings.id, { onDelete: 'cascade' }),
  chunkIndex: integer('chunk_index').notNull(),
  chunkText: text('chunk_text').notNull(),
  vector: blob('vector'),
  model: text('model').notNull().default('local'),
  createdAt: text('created_at').notNull(),
});

export const conversations = sqliteTable('conversations', {
  id: text('id').primaryKey(),
  title: text('title'),
  recordingId: text('recording_id').references(() => recordings.id, { onDelete: 'cascade' }),
  createdAt: text('created_at').notNull(),
});

export const conversationMessages = sqliteTable('conversation_messages', {
  id: text('id').primaryKey(),
  conversationId: text('conversation_id')
    .notNull()
    .references(() => conversations.id, { onDelete: 'cascade' }),
  role: text('role').notNull(),
  content: text('content').notNull(),
  sourceRecordingIds: text('source_recording_ids'),
  attachments: text('attachments'),
  createdAt: text('created_at').notNull(),
});

export const imports = sqliteTable('imports', {
  id: text('id').primaryKey(),
  recordingId: text('recording_id').references(() => recordings.id, { onDelete: 'set null' }),
  originalFileName: text('original_file_name').notNull(),
  fileType: text('file_type').notNull(),
  filePath: text('file_path').notNull(),
  extractedText: text('extracted_text'),
  createdAt: text('created_at').notNull(),
});

export const streaks = sqliteTable('streaks', {
  date: text('date').primaryKey(),
  recordingCount: integer('recording_count').notNull().default(0),
});

export const comments = sqliteTable('comments', {
  id: text('id').primaryKey(),
  recordingId: text('recording_id')
    .notNull()
    .references(() => recordings.id, { onDelete: 'cascade' }),
  content: text('content').notNull(),
  timestamp: real('timestamp'),
  createdAt: text('created_at').notNull(),
});

export const savedPrompts = sqliteTable('saved_prompts', {
  id: text('id').primaryKey(),
  title: text('title').notNull(),
  promptText: text('prompt_text').notNull(),
  createdAt: text('created_at').notNull(),
});

export const attachments = sqliteTable('attachments', {
  id: text('id').primaryKey(),
  recordingId: text('recording_id')
    .notNull()
    .references(() => recordings.id, { onDelete: 'cascade' }),
  fileName: text('file_name').notNull(),
  filePath: text('file_path').notNull(),
  fileType: text('file_type').notNull(),
  sizeBytes: integer('size_bytes').default(0),
  createdAt: text('created_at').notNull(),
});

export const calendarEvents = sqliteTable('calendar_events', {
  id: text('id').primaryKey(),
  googleCalendarId: text('google_calendar_id'),
  title: text('title').notNull(),
  description: text('description'),
  startTime: text('start_time').notNull(),
  endTime: text('end_time').notNull(),
  location: text('location'),
  meetLink: text('meet_link'),
  attendees: text('attendees'),
  autoRecord: integer('auto_record', { mode: 'boolean' }).notNull().default(false),
  recordingId: text('recording_id').references(() => recordings.id, { onDelete: 'set null' }),
  status: text('status').default('confirmed'),
  syncedAt: text('synced_at').notNull(),
});

export const settings = sqliteTable('settings', {
  key: text('key').primaryKey(),
  value: text('value').notNull(),
});

// Type exports
export type Recording = typeof recordings.$inferSelect;
export type NewRecording = typeof recordings.$inferInsert;
export type Transcript = typeof transcripts.$inferSelect;
export type NewTranscript = typeof transcripts.$inferInsert;
export type Translation = typeof translations.$inferSelect;
export type AIOutput = typeof aiOutputs.$inferSelect;
export type Tag = typeof tags.$inferSelect;
export type Conversation = typeof conversations.$inferSelect;
export type ConversationMessage = typeof conversationMessages.$inferSelect;
export type Import = typeof imports.$inferSelect;
export type Comment = typeof comments.$inferSelect;
export type Streak = typeof streaks.$inferSelect;
export type SavedPrompt = typeof savedPrompts.$inferSelect;
export type Attachment = typeof attachments.$inferSelect;
export type CalendarEvent = typeof calendarEvents.$inferSelect;
export type NewCalendarEvent = typeof calendarEvents.$inferInsert;
